name: Build HIDENET APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip *.zip -d project

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Find project folder
        run: |
          cd project
          PROJECT_DIR=$(find . -name gradlew | head -n 1 | xargs dirname)
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Build APK
        run: |
          cd project/$PROJECT_DIR
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HIDENET-APK
          path: project/**/build/outputs/apk/debug/*.apk
